/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on Oct 3, 2014, 8:34:48 AM
 */
package hkt.project;

import javax.swing.JScrollPane;

/**
 *
 * @author Dell
 */
public class PanelStart extends javax.swing.JPanel {

    /** Creates new form Start */
    public PanelStart() {
        initComponents();
        jTextArea1.setEditable(false);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 237, 255));
        setMaximumSize(new java.awt.Dimension(435, 302));
        setMinimumSize(new java.awt.Dimension(435, 302));
        setPreferredSize(new java.awt.Dimension(435, 302));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Cam kết bản quyền");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nĐiều 1 : Điều kiện sử dụng\nKhi cài đặt phần mềm HKT, quý khách hàng đã đồng ý những cam kết được quy định trong các điều khoản sau đây.\n\nĐiều 2 : Bản quyền sử dụng\nBản quyền sử dụng cho phép khách hàng cài đặt trên một phương tiện duy nhất (máy tính hoặc thiết bị khác) mà khách hàng chỉ định và thỏa thuận ban đầu.\nBản quyền sử dụng được cấp vĩnh viễn hoặc theo thời hạn tùy theo thỏa thuận.\n\nĐiều 3 : Quyền hạn sử dụng\nKhách hàng chỉ sở hữu quyền sử dụng phiên bản phần mềm cam kết.\nKhách hàng cam kết không chỉnh sửa, tái sản xuất hay thương mại hóa phần mềm, toàn bộ hay một phần bất kỳ nào đó.\nKhách hàng cam kết không chuyển nhượng, cho thuê, cho mượn …. quyền sử dụng phần mềm khi không được sự chấp thuận bằng văn bản của Công ty Cổ phần Tư vấn Quản trị HKT.\nMọi hành vi sử dụng với những mục đích ngoài cam kết thỏa thuận trong hợp đồng đều do khách hàng tự chịu trách nhiệm và bồi thường theo cam kết và theo quy định của pháp luật.\n\nĐiều 4 : Bảo hành và hỗ trợ sử dụng\nPhần mềm được bảo hành và hỗ trợ sử dụng miễn phí trong thời gian cam kết theo hợp đồng ký kết giữa khách hàng và Công ty Cổ phần Tư vấn Quản trị HKT tính từ ngày nghiệm thu cài đặt chương trình phần mềm.\n\nĐiều 5 : Bảo trì mở rộng\nSau thời hạn bảo hành miễn phí, khách hàng có thể ký hợp đồng cung cấp dịch vụ bảo trì và hỗ trợ sử dụng hàng năm với mức chi phí thỏa thuận.\n\nĐiều 6 : Giải quyết tranh chấp\nNhững vấn đề phát sinh trong sẽ được bàn bạc thỏa thuận và bổ sung bằng văn bản giữa khách hàng và Công ty Cổ phần Tư vấn Quản trị HKT. Các tranh chấp không thể thương lượng được thì sẽ đưa ra Toà án kinh tế Thành phố Hà Nội – Việt Nam.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Để cài đặt, quý khách cần chấp nhận cam kết bản quyền phần mềm HKT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
